
            <div style="background-color:#0067A9; height:30px;border-top-left-radius:15px;border-top-right-radius:15px;padding-top:5px;">
                <h7>Rotary - A Brief History</h7>
            </div>
            <div style="padding:10px;">
              <div>
                <p>The world's first service club, the Rotary Club of   Chicago, Illinois, USA, was formed on 23 February 1905 by Paul P.   Harris, an attorney who wished to recapture in a professional club the   same friendly spirit he had felt in the small towns of his youth. The   name &quot;Rotary&quot; derived from the early practice of rotating meetings among   members' offices.</p>
                <p>Rotary's popularity spread throughout the United   States in the decade that followed; clubs were chartered from San   Francisco to New York. By 1921, Rotary clubs had been formed on six   continents, and the organization adopted the name Rotary International a   year later.</p>
                <p>As Rotary grew, its mission expanded beyond serving   the professional and social interests of club members. Rotarians began   pooling their resources and contributing their talents to help serve   communities in need. The organization's dedication to this ideal is best   expressed in its principal motto: Service Above Self. Rotary also later   embraced a code of ethics, called The 4-Way Test, that has been   translated into hundreds of languages.</p>
                <p>During and after World War II, Rotarians became   increasingly involved in promoting international understanding. In 1945,   49 Rotary members served in 29 delegations to the United Nations   Charter Conference. Rotary still actively participates in UN conferences   by sending observers to major meetings and promoting the United Nations   in Rotary publications. Rotary International's relationship with the   United Nations Educational, Scientific, and Cultural Organization   (UNESCO) dates back to a 1943 London Rotary conference that promoted   international cultural and educational exchanges. Attended by ministers   of education and observers from around the world, and chaired by a past   president of RI, the conference was an impetus to the establishment of   UNESCO in 1946.</p>
                <p>An endowment fund, set up by Rotarians in 1917 &quot;for   doing good in the world,&quot; became a not-for-profit corporation known as   The Rotary Foundation in 1928. Upon the death of Paul Harris in 1947, an   outpouring of Rotarian donations made in his honor, totaling US$2   million, launched the Foundation's first program &mdash; graduate fellowships,   now called Ambassadorial Scholarships. Today, contributions to The   Rotary Foundation total more than US$80 million annually and support a   wide range of humanitarian grants and educational programs that enable   Rotarians to bring hope and promote international understanding   throughout the world.</p>
                <p>In 1985, Rotary made a historic commitment to immunize   all of the world's children against polio. Working in partnership with   nongovernmental organizations and national governments thorough its   PolioPlus program, Rotary is the largest private-sector contributor to   the global polio eradication campaign. Rotarians have mobilized hundreds   of thousands of PolioPlus volunteers and have immunized more than one   billion children worldwide. By the 2010 target date for certification of   a polio-free world, Rotary will have contributed close to&nbsp;a billion   dollars to the cause.</p>
                <p>As it approached the dawn of the 21st century, Rotary   worked to meet the changing needs of society, expanding its service   effort to address such pressing issues as environmental degradation,   illiteracy, world hunger, and children at risk. The organization   admitted women for the first time (worldwide) in 1989 and claims more   than 170,000 women in its ranks today. Following the collapse of the   Berlin Wall and the dissolution of the Soviet Union, Rotary clubs were   formed or re-established throughout Central and Eastern Europe. Today,   1.2 million Rotarians belong to some 33,000 Rotary clubs in 200   countries.</p>
              </div>
              <p>&nbsp;</p>
</div>
